### ISSUE TITLE
Wrong parameter for Currency

### ISSUE THREAD

**Issue by fherken** [managed-components/bing#9]
The "Currency" is sent to bing as a parameter which is called "gvc" but according to the documentation of Bing (https://help.ads.microsoft.com/apex/index/3/en/53056/) it should be called "gc". Therefore our currency is not recognized at Bing and not shown in the events.

I tried to manually change gvc to gc and then the currency is sent correctly.

Documentation from Bing:
![image](https://github.com/user-attachments/assets/a46f3c33-e45c-487c-bce7-80cebbb6a00a)

ReadMe of component:
![image](https://github.com/user-attachments/assets/1cc7098e-3214-4dac-9165-01bdd808c0de)

**Comment by bjesus** [comment]
Thanks, this should be fixed now on the Zaraz side. I'll update the README here
